[server]
headless = true
enableCORS = false

enableXsrfProtection = false

# Aşağısı yeni ekleme:
address = "0.0.0.0"
port    = 8501



[theme]
primaryColor = "#ff4b4b"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"
